name: mcDungeons
main: com.coffeejawa.mcDungeons.mcDungeons
version: 0.5
authors: [tumland]
description: mcDungeons allows servers to control difficulty of monsters on a region granularity. It also enables dungeon creation by placing blocks to represent different spawn types.

softdepend: [ WorldGuard ]

commands:
    mcd:
        description: Root command for all mcDungeons Commands.
        aliases: mcd
        usage: /mcd <region|level|debug> [add|set|list|reset|remove]
        permission: mcd.help
        permission-message: You require permission mcd.help to do that.
        
permissions:
    mcd.*:
        description: Gives access to all mcDungeons commands/functions.
        default: op
        children:
            mcd.debug: true
            mcd.help: true
            mcd.regions: true
            mcd.levels: true
            mcd.dungeons: true

    mcd.regions:
        description: Allows user to configure mcDungeons regions.
        default: false
        
    mcd.levels:
        description: Allows user to configure mcDungeons levels.
        default: false
        
    mcd.dungeons:
        description: Allows user to configure mcDungeons dungeons.
        default: false
            
    mcd.debug:
        description: Allows user to toggle debug on and off.
        default: false

    mcd.help:
        description: Allows user to view command help text.
        default: false
